### PR TITLE
feat: start recording when fully joined

### PR DESCRIPTION
**Pull request by sahibkhokhar**
### TL;DR
Enhanced Zoom meeting recording reliability by improving timing and validation checks

### What changed?
- Increased wait times between actions from 500ms to 700ms for better stability
- Added validation to ensure the "Leave" button is properly labeled before starting recording
- Added logging to confirm when the meeting is ready for recording
- Clarified comment about meeting end check frequency

### How to test?
1. Run the bot with the updated Zoom meeting URL
2. Verify the bot successfully:
   - Joins the meeting
   - Waits for proper button labeling
   - Starts recording
   - Monitors for meeting end
3. Confirm the recording starts only after the leave button is properly detected

### Why make this change?
To improve the reliability of the recording process by ensuring all UI elements are properly loaded and labeled before taking actions. This prevents potential race conditions and improves the overall stability of the recording bot.

Completes MEE-74

### CODE REVIEW

**Comment by sahibkhokhar** [comment]
* **#32** <a href="https://app.graphite.dev/github/pr/meetingbot/meetingbot/32?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/meetingbot/meetingbot/32?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by owengretzinger — APPROVED** [review]
LGTM but I wonder if there's a better to do it instead of hard coding 700ms.

**Comment by sahibkhokhar** [comment]
will take a look, the wait command for some reason does not work all the time for this button, so I was putting a timer instead, I think it will require a different thing to wait for

**Comment by sahibkhokhar** [comment]
### Merge activity

* **Nov 19, 3:39 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/meetingbot/meetingbot/32).

**Pull request merged**
