### PR TITLE
task: updated SRS to reflect true P0 requirements

### PR DESCRIPTION
**Pull request by sarahsimionescu**

### CODE REVIEW

**Comment by sarahsimionescu** [comment]
* **#29** <a href="https://app.graphite.dev/github/pr/meetingbot/meetingbot/29?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sarahsimionescu and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by sahibkhokhar** [comment]
don't we already have video basically? so does it need to be a requirement way later?

**Comment by sarahsimionescu** [comment]
@sahibkhokhar good point, that's true, the bots do record both. I would accept this for now bc we need it upated for our presentation and we can keep it in mind for the next update.

**Review by sahibkhokhar — APPROVED** [review]

**Comment by sarahsimionescu** [comment]
### Merge activity

* **Nov 12, 1:46 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/meetingbot/meetingbot/29).

**Pull request merged**
